### ISSUE TITLE
Cannot launch on Ubuntu 14.10

### ISSUE THREAD

**Issue by bocajnotnef** [TechnitiumSoftware/BitChatClient#1]
Hello! Just saw the blog post introducing BitChat on Reddit and thought I'd give it a spin. Unfortunately I cannot seem to launch it on Ubuntu 14.10.

Error from launching `start.sh` and `install.sh` is:

```
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

Made sure Mono was installed and updated--Not sure what else it could be.

**Comment by bocajnotnef** [comment]
Hmm. interestingly, `install.sh` doesn't seem to install the things. After running it I ran `apt-get install mono-complete` to find that it wasn't installed.

After installing mono-complete manually and running `install.sh` I'm prompted to make a profile.

So, really, issue here is `install.sh` does not, in fact, install.

**Comment by ShreyasZare** [comment]
Hi,

The install.sh is not really an installer (I am intending to make it a proper installer later). It does only two tasks: to install mono-complete and import root certificates into mono's certificate store. Mono doesn't have any trusted certificates by default.

I am planing a blog post with instructions for Linux users to help them with this.

Thanks,

**Comment by shiwangkalkhanda** [comment]
Hi, 
     You can also try new updated install script which also adds a menu entry and simplify the installation process. Nevertheless it is a great chat app.

**Comment by ShreyasZare** [comment]
Closing this issue as mono framework is no more supported by the new Mesh project.
