### ISSUE TITLE
Profile Registration fails

### ISSUE THREAD

**Issue by x-solid** [TechnitiumSoftware/BitChatClient#11]
BitChat has a great concept, so I would like to give BitChat a try. Unfortunatly registration fails with error message:

"Error occurred while registering for profile certificate: 
The remote server returned an error: (404) Not Found."

**Comment by ShreyasZare** [comment]
Thanks for the post. Bit Chat has been discontinued on Nov 11, 2019 and will be replaced by Mesh IM which will be available soon. Only new Bit Chat profile registrations are affected while users who already have registered profiles can keep using them with Bit Chat until they expire.

**Comment by ShreyasZare** [comment]
Mesh is now released! Get it from [mesh.im](http://mesh.im)
