### ISSUE TITLE
Profile generation issue: auth/decryption fails

### ISSUE THREAD

**Issue by bocajnotnef** [TechnitiumSoftware/BitChatClient#2]
When making a profile
![screenshot from 2015-05-11 12 57 39](https://cloud.githubusercontent.com/assets/2142082/7570337/53f69d02-f7dd-11e4-9564-08fc471871a2.png)

**Comment by ShreyasZare** [comment]
This error occurs due to Mono framework not having any trusted root certificate in its certificate store. Use this command below to import root certificates:

mozroots --import --ask-remove

If you run install.sh as root, then this issue will not occur.
